#!/usr/bin/env zsh

if [[ ! `echo $SHELL | grep "\/zsh$"` ]]; then
  echo "Must be running zsh: chsh -s `which zsh`"
  exit 1
fi

if [[ ! -d "${ZDOTDIR:-$HOME}"/.zprezto ]]; then
  git clone --recursive https://github.com/jfilip/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    if [[ ! -f "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    elif [[ ! -L "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
      mv "${ZDOTDIR:-$HOME}/.${rcfile:t}" "${ZDOTDIR:-$HOME}/.${rcfile:t}.bak"
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    fi
  done
fi

if [[ -d "${HOME}"/Library/Application\ Support/iTerm2/DynamicProfiles ]]; then
  ln -s "${PWD}"/iterm_profile-jkitty.json "${HOME}"/Library/Application\ Support/iTerm2/DynamicProfiles/
fi

for rcfile in "${PWD}"/rcfiles/.*; do
  [[ ! -f "${HOME}/`basename $rcfile`" ]] && cp $rcfile "${HOME}/"
done
