#!/usr/bin/env zsh

if [[ ! `echo $SHELL | grep "\/zsh$"` ]]; then
  echo "Must be running zsh: chsh -s `which zsh`"
  exit 1
fi

if [[ ! -d "${ZDOTDIR:-$HOME}"/src/cli_tools ]]; then
  [[ ! -d "${ZDOTDIR:-$HOME}"/src ]] && mkdir "${ZDOTDIR:-$HOME}"/src
  cd "${ZDOTDIR:-$HOME}"/src
  git clone https://github.com/jfilip/cli_tools.git
  cd -
fi

if [[ ! -d "${ZDOTDIR:-$HOME}"/.zprezto ]]; then
  git clone --recursive https://github.com/jfilip/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    if [[ ! -f "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    elif [[ ! -L "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
      mv "${ZDOTDIR:-$HOME}/.${rcfile:t}" "${ZDOTDIR:-$HOME}/.${rcfile:t}.bak"
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    fi
  done
fi

iterm_profile_path="${HOME}/Library/Application Support/iTerm2/DynamicProfiles"
iterm_profile_file="iterm_profile-jkitty.json"

if [[ -d "$iterm_profile_path" && ! -f "${iterm_profile_path}/${iterm_profile_file}" ]]; then
  ln -s "${PWD}/${iterm_profile_file}" "$iterm_profile_path/"
fi

for rcfile in "${PWD}"/rcfiles/.*; do
  [[ ! -f "${HOME}/${rcfile:t}" ]] && ln -s $rcfile "${HOME}/${rcfile:t}"
done
